"""
Generate the general-purpose shell32 seed corpus at corpus/seeds/.

Coverage goal: every operator group in mutate.h has at least one seed whose layout
satisfies the operator's precondition. The pylnk3 part of this script handles the bulk
of the basic shapes (filesystem path, env-var path, env-var icon, property store).
The hand-rolled parts cover the eight ExtraData blocks pylnk3 won't write (Console,
ConsoleFE, Tracker, SpecialFolder, Darwin, Shim, KnownFolder, VistaIDL) plus
structural variants (ANSI, ForceNoLinkInfo, multi-block, deep PIDL).

The Darwin campaign has its own corpus generated by generate_seeds_darwin.py — but
we drop a Darwin-block-bearing seed here too so harness.cpp's CopyDataBlock pass
exercises the structural decode of 0xA0000006 in shell32.

Run from the project root:
    python tools/generate_seeds.py
"""
import os
import struct
import sys

import pylnk3

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _lnk_helpers import (
    block_environment, block_console, block_console_fe, block_tracker,
    block_special_folder, block_darwin, block_icon_environment, block_shim,
    block_property_store_minimal, block_known_folder, block_vista_idlist,
    shitemid_clsid, shitemid_cpl_descriptor, shitemid_filesystem_dir,
    shitemid_filesystem_file, build_idlist, with_idlist_size, build_header,
    build_string_data, CLSID_MY_COMPUTER, CLSID_CONTROL_PANEL, CLSID_RECYCLE_BIN,
    CLSID_NETWORK, FOLDERID_ControlPanelFolder, FOLDERID_Documents,
    FOLDERID_Desktop, FOLDERID_PrintersFolder, CSIDL_DESKTOP, CSIDL_CONTROLS,
    CSIDL_FONTS,
    LF_HAS_LINK_TARGET_IDLIST, LF_HAS_LINK_INFO, LF_HAS_NAME,
    LF_HAS_RELATIVE_PATH, LF_HAS_WORKING_DIR, LF_HAS_ARGUMENTS,
    LF_HAS_ICON_LOCATION, LF_IS_UNICODE, LF_FORCE_NO_LINK_INFO,
    LF_HAS_EXP_STRING, LF_HAS_DARWIN_ID, LF_HAS_EXP_ICON,
)

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       '..', 'corpus', 'seeds')
OUT_DIR = os.path.abspath(OUT_DIR)
os.makedirs(OUT_DIR, exist_ok=True)


def write(name, data):
    path = os.path.join(OUT_DIR, name)
    with open(path, 'wb') as f:
        f.write(data)
    print(f'  wrote {name} ({len(data)} bytes)')


# ===========================================================================
# Section 1: pylnk3 baselines.
# Filesystem-shortcut family — different flag combinations to seed the FLAGS,
# OFFSETS, SIZES, and PIDL groups with diverse starting points.
# ===========================================================================
print('=== pylnk3 baselines ===')

def pylnk_save_fs(name, target, *, args=None, work_dir=None,
                  description=None, icon=None, icon_index=0):
    """pylnk3.for_file is a thin wrapper that builds a filesystem shortcut.
    We pass everything optionally so the resulting set of files has different
    LinkFlag profiles."""
    lnk = pylnk3.for_file(target, lnk_name=os.path.join(OUT_DIR, name),
                          arguments=args, work_dir=work_dir,
                          description=description, icon_file=icon,
                          icon_index=icon_index)
    print(f'  wrote {name}')

# Plain filesystem shortcut, full string set
pylnk_save_fs('01_fs_full.lnk',
              r'C:\Windows\System32\notepad.exe',
              args='--help', work_dir=r'C:\Windows\System32',
              description='Notepad',
              icon=r'C:\Windows\System32\notepad.exe', icon_index=0)

# Filesystem shortcut, minimal flags
pylnk_save_fs('02_fs_minimal.lnk', r'C:\Windows\notepad.exe')

# Filesystem shortcut, args present, no working dir or icon
pylnk_save_fs('03_fs_args_only.lnk',
              r'C:\Windows\System32\cmd.exe',
              args='/c echo hello && pause')

# Long arguments string (>260 chars) — exercises the uncapped Args field
long_args = ' '.join(f'--flag{i}=value{i}' for i in range(40))
pylnk_save_fs('04_fs_long_args.lnk',
              r'C:\Windows\System32\cmd.exe', args=long_args)

# Path with embedded spaces — CVE-2015-0096-style trigger surface
pylnk_save_fs('05_fs_spaces_in_path.lnk',
              r'C:\Program Files\Common Files\System\target.exe',
              args='   ')


# ===========================================================================
# Section 2: pylnk3 + raw ExtraData injection.
# pylnk3 builds a base LNK; we splice in raw block bytes immediately before the
# ExtraData terminator. Works because the LNK ends with a 4-byte zero terminator
# we can locate by scanning from the end.
# ===========================================================================
print('=== pylnk3 base + raw ExtraData splices ===')

def splice_extra_data(lnk_bytes, *blocks):
    """Insert raw ExtraData block bytes immediately before the trailing terminator.
    The on-disk ExtraData section ends with a 4-byte zero; we strip it, append our
    blocks, and re-add the terminator."""
    if lnk_bytes.endswith(b'\x00\x00\x00\x00'):
        body = lnk_bytes[:-4]
    else:
        body = lnk_bytes
    return body + b''.join(blocks) + b'\x00\x00\x00\x00'


def make_via_pylnk3(target=r'C:\Windows\notepad.exe', **kw):
    import io
    lnk = pylnk3.for_file(target, **kw)
    buf = io.BytesIO()
    lnk.write(buf)
    return buf.getvalue()


# Tracker block: distributed link tracking. Drives GROUP_TRACKER operators.
base = make_via_pylnk3()
write('06_with_tracker.lnk', splice_extra_data(base, block_tracker()))

# Tracker with attacker-style MachineID — exercises the NetBIOS-resolution code
# path in the parser even though we don't actually do DLT.
write('07_with_tracker_attacker_machineid.lnk',
      splice_extra_data(base, block_tracker(machine_id='ATTACKER-PC')))

# SpecialFolder block: legacy CSIDL system. CVE-2017-8464 surface.
write('08_with_specialfolder_controls.lnk',
      splice_extra_data(base, block_special_folder(csidl=CSIDL_CONTROLS)))

write('09_with_specialfolder_desktop.lnk',
      splice_extra_data(base, block_special_folder(csidl=CSIDL_DESKTOP)))

# KnownFolder block: post-Vista replacement. Same CVE surface, different identifier.
write('10_with_knownfolder_documents.lnk',
      splice_extra_data(base, block_known_folder(folder_id=FOLDERID_Documents)))

write('11_with_knownfolder_controlpanel.lnk',
      splice_extra_data(base, block_known_folder(folder_id=FOLDERID_ControlPanelFolder)))

# Console + ConsoleFE — exercises 0xA0000002 / 0xA0000004 decoders.
write('12_with_console.lnk',
      splice_extra_data(base, block_console(), block_console_fe(437)))

# Shim block — exercises 0xA0000008 layer-name decoder.
write('13_with_shim.lnk', splice_extra_data(base, block_shim('RUNASINVOKER')))

# Darwin block — even in the shell32 corpus, so harness.cpp's CopyDataBlock(0xA0000006)
# pass has a target. The actual MSI parsing happens in the darwin corpus.
write('14_with_darwin.lnk', splice_extra_data(base, block_darwin()))

# IconEnvironment + EnvironmentVariable blocks
write('15_with_envvars.lnk',
      splice_extra_data(base, block_environment(), block_icon_environment()))

# PropertyStore block (additional, on top of pylnk3's own which it sometimes emits)
write('16_with_propstore.lnk',
      splice_extra_data(base, block_property_store_minimal()))

# All the niche blocks at once — feeds GROUP_EXTRA_SEQ (reorder, duplicate, insert).
write('17_kitchen_sink.lnk',
      splice_extra_data(base,
                        block_environment(),
                        block_console(),
                        block_console_fe(),
                        block_tracker(),
                        block_special_folder(),
                        block_darwin(),
                        block_icon_environment(),
                        block_shim(),
                        block_property_store_minimal(),
                        block_known_folder()))


# ===========================================================================
# Section 3: hand-built LNKs for shapes pylnk3 cannot represent.
# ===========================================================================
print('=== hand-built LNKs ===')

def build_lnk(*, link_flags, idlist=None, link_info=None,
              strings=None, extra_blocks=()):
    """Assemble a complete LNK from parts. `strings` is a dict of
    {bit: value} where bit is one of LF_HAS_NAME, LF_HAS_RELATIVE_PATH, etc."""
    out = build_header(link_flags)
    if idlist is not None:
        out += with_idlist_size(idlist)
    if link_info is not None:
        out += link_info
    if strings:
        is_uni = bool(link_flags & LF_IS_UNICODE)
        for bit in (LF_HAS_NAME, LF_HAS_RELATIVE_PATH, LF_HAS_WORKING_DIR,
                    LF_HAS_ARGUMENTS, LF_HAS_ICON_LOCATION):
            if link_flags & bit and bit in strings:
                out += build_string_data(strings[bit], is_uni)
    for b in extra_blocks:
        out += b
    out += b'\x00\x00\x00\x00'  # ExtraData terminator
    return out


# 18: ANSI seed (no Unicode flag). Drives MUTATE_FLAG_DESYNC_ISUNICODE — flipping
# the bit on this seed reinterprets ANSI strings as Unicode, which is an
# interesting parser stress.
ansi_idl = build_idlist([shitemid_clsid(CLSID_MY_COMPUTER)])
write('18_ansi_strings.lnk',
      build_lnk(
          link_flags=LF_HAS_LINK_TARGET_IDLIST | LF_HAS_NAME
                     | LF_HAS_RELATIVE_PATH | LF_HAS_ARGUMENTS,
          idlist=ansi_idl,
          strings={
              LF_HAS_NAME:          'ANSI shortcut',
              LF_HAS_RELATIVE_PATH: r'..\target.exe',
              LF_HAS_ARGUMENTS:     '/ansi /params',
          }))

# 19: ForceNoLinkInfo — IDList only, no LinkInfo block, flag tells parser to
# skip LinkInfo lookup. Tests the early-exit branch.
fs_idl = build_idlist([
    shitemid_clsid(CLSID_MY_COMPUTER),
    shitemid_filesystem_dir('Program Files'),
    shitemid_filesystem_dir('Common'),
    shitemid_filesystem_file('app.exe'),
])
write('19_forcenolinkinfo.lnk',
      build_lnk(
          link_flags=(LF_HAS_LINK_TARGET_IDLIST | LF_FORCE_NO_LINK_INFO
                      | LF_IS_UNICODE),
          idlist=fs_idl))

# 20: HasExpString — environment-variable expansion path
write('20_has_exp_string.lnk',
      build_lnk(
          link_flags=(LF_HAS_LINK_TARGET_IDLIST | LF_HAS_RELATIVE_PATH
                      | LF_HAS_EXP_STRING | LF_IS_UNICODE),
          idlist=fs_idl,
          strings={LF_HAS_RELATIVE_PATH: r'..\target.exe'},
          extra_blocks=[block_environment(r'%TEMP%\dropper.exe')]))

# 21: HasExpIcon — environment-variable icon path
write('21_has_exp_icon.lnk',
      build_lnk(
          link_flags=(LF_HAS_LINK_TARGET_IDLIST | LF_HAS_EXP_ICON
                      | LF_IS_UNICODE),
          idlist=fs_idl,
          extra_blocks=[block_icon_environment(r'%LOCALAPPDATA%\icon.ico')]))

# 22: Stuxnet PIDL pattern — [MyComputer, ControlPanel, CPL applet].
# The CPL applet's class type is 0x00 (delegate), which is precisely the
# dispatch path CVE-2010-2568 exploited.
stuxnet_idl = build_idlist([
    shitemid_clsid(CLSID_MY_COMPUTER),
    shitemid_clsid(CLSID_CONTROL_PANEL),
    shitemid_cpl_descriptor(r'\\.\STORAGE#Volume#stuxnet\applet.cpl'),
])
write('22_stuxnet_pattern.lnk',
      build_lnk(
          link_flags=LF_HAS_LINK_TARGET_IDLIST | LF_IS_UNICODE,
          idlist=stuxnet_idl))

# 23: CVE-2017-8464 pattern — SpecialFolder + KnownFolder both pointing at
# Control Panel, PIDL containing a CPL-like descriptor. Forces namespace
# context switch through both legacy and modern identifier systems.
write('23_cve_2017_8464.lnk',
      build_lnk(
          link_flags=LF_HAS_LINK_TARGET_IDLIST | LF_IS_UNICODE,
          idlist=stuxnet_idl,
          extra_blocks=[
              block_special_folder(csidl=CSIDL_CONTROLS, offset=0x14),
              block_known_folder(folder_id=FOLDERID_ControlPanelFolder, offset=0x14),
          ]))

# 24: deep PIDL chain (10 items) — drives MUTATE_PIDL_DEPTH and CHAIN_TRUNCATION
deep_items = [shitemid_clsid(CLSID_MY_COMPUTER)]
for i in range(8):
    deep_items.append(shitemid_filesystem_dir(f'level{i}'))
deep_items.append(shitemid_filesystem_file('deep.txt'))
deep_idl = build_idlist(deep_items)
write('24_deep_pidl.lnk',
      build_lnk(
          link_flags=LF_HAS_LINK_TARGET_IDLIST | LF_IS_UNICODE,
          idlist=deep_idl))

# 25: Vista IDList block — 0xA000000C carries a duplicate IDList that overrides
# the legacy one on Vista+. Parser exercises both.
write('25_vista_idlist.lnk',
      build_lnk(
          link_flags=LF_HAS_LINK_TARGET_IDLIST | LF_IS_UNICODE,
          idlist=stuxnet_idl,
          extra_blocks=[block_vista_idlist(stuxnet_idl)]))

# 26: CLSID-only IDList — single item, root-level. Tests CLSID-rooted resolution.
write('26_clsid_only_recyclebin.lnk',
      build_lnk(
          link_flags=LF_HAS_LINK_TARGET_IDLIST | LF_IS_UNICODE,
          idlist=build_idlist([shitemid_clsid(CLSID_RECYCLE_BIN)])))

# 27: header field exotica — non-zero hot key, minimized show_cmd, file size
write('27_header_exotica.lnk',
      build_header(
          link_flags=LF_HAS_LINK_TARGET_IDLIST | LF_IS_UNICODE,
          file_attributes=0x00000080, file_size=0xFFFFFFFF,
          icon_index=42, show_cmd=7, hot_key=0x4170)  # F10
      + with_idlist_size(fs_idl)
      + b'\x00\x00\x00\x00')

# 28: empty IDList (just the terminator) — boundary case
write('28_empty_idlist.lnk',
      build_lnk(
          link_flags=LF_HAS_LINK_TARGET_IDLIST | LF_IS_UNICODE,
          idlist=build_idlist([])))

# 29: HasDarwinID flag set + DarwinDataBlock present (the spec-correct combo).
# This trips the LinkFlags-gated decode path that flag-only seeds and
# block-only seeds each miss.
write('29_darwin_with_flag.lnk',
      build_lnk(
          link_flags=(LF_HAS_LINK_TARGET_IDLIST | LF_HAS_DARWIN_ID
                      | LF_IS_UNICODE),
          idlist=fs_idl,
          extra_blocks=[block_darwin()]))

print(f'\nDone. {len(os.listdir(OUT_DIR))} files in {OUT_DIR}')
